### ISSUE TITLE
エラーがある場合はstatusに表す

### ISSUE THREAD

**Issue by buildsville** [showcase-gig-platform/custom-metrics-generator#1]
cronフォーマットの不整合などでエラーになった場合など、リソースのステータスに表示する
argocdのカスタムヘルスチェックも作っておきたい

**Comment by buildsville** [comment]
```
status:
  conditions:
    - type:なんか決まったstring
      status: なんか決まったstring
      reason: string
      message: string
      lastTransitionTime: timestamp
```

この形が業界のベーシックっぽい？ timestampはあったりなかったり
